title: Justin Yu
owner: Justin Yu
email: justinyu@mit.edu
description: My portfolio website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://justinyu1618.github.io/personal_website2/" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username:
disqus_username: 

# Build settings
markdown: kramdown
# theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->

collections:
  - projects